In [13]:
import numpy as np
a=np.arange(1,11,2)
np.array(a)

array([1, 3, 5, 7, 9])

In [14]:
np.shape(a)

(5,)

In [15]:
np.ndim(a)

1

In [32]:
b=[[5,6],[2,3]]
b=np.array(b)

In [33]:
np.shape(b)

(2, 2)

In [34]:
np.ndim(b)

2

In [35]:
type(b)

numpy.ndarray

In [36]:
np.size(b)

4

In [41]:
c=[[25,3],[9,6],[2,65]]
c=np.array(c)
c

array([[25,  3],
       [ 9,  6],
       [ 2, 65]])

In [42]:
np.shape(c)

(3, 2)

In [43]:
np.ndim(c)

2

In [45]:
np.linspace(2,51,5)

array([ 2.  , 14.25, 26.5 , 38.75, 51.  ])

In [47]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [48]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
z=np.array(np.random.randint(200,852,3))
z


array([454, 624, 496])

In [54]:
type(z)

numpy.ndarray

In [61]:
v=np.array([5,4,2,6,9])
v

array([5, 4, 2, 6, 9])

In [63]:
v=np.append(v,5)
v

array([5, 4, 2, 6, 9, 5])

In [65]:
v=np.append(v,[85,45,12,63])
v

array([ 5,  4,  2,  6,  9,  5, 85, 45, 12, 63])

In [68]:
v[[2,4]]=[99,101]
v

array([  5,   4,  99,   6, 101,   5,  85,  45,  12,  63])

In [69]:
np.ndim(v)

1

In [71]:
v=np.delete(v,6)
v

array([  5,   4,  99,   6, 101,   5,  45,  12,  63])

In [72]:
x=np.sort(v)
x

array([  4,   5,   5,   6,  12,  45,  63,  99, 101])

In [96]:
m=np.array([[13,2,3],[43,5,6]])
m

array([[13,  2,  3],
       [43,  5,  6]])

In [74]:
np.ndim(m)

2

In [76]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
m[1,1]

5

In [91]:
np.shape(m)

(2, 3)

In [84]:
m[1:2]

array([[4, 5, 6]])

In [85]:
o=np.ravel(m)
o

array([1, 2, 3, 4, 5, 6])

In [92]:
m=m.T

In [93]:
np.shape(m)

(3, 2)

In [94]:
m

array([[1, 4],
       [2, 5],
       [3, 6]])

In [97]:
np.sort(m,axis=0)

array([[13,  2,  3],
       [43,  5,  6]])

In [98]:
np.sort(m,axis=1)

array([[ 2,  3, 13],
       [ 5,  6, 43]])

In [106]:
k=np.ones([2,2])
k

array([[1., 1.],
       [1., 1.]])

In [107]:
np.ndim(k)

2

In [108]:
np.shape(k)

(2, 2)

In [118]:
kl=np.array([[69,65,32],[1,2,8]])
kl

array([[69, 65, 32],
       [ 1,  2,  8]])

In [119]:
np.vstack((m,kl))

array([[13,  2,  3],
       [43,  5,  6],
       [69, 65, 32],
       [ 1,  2,  8]])

In [120]:
np.hstack((m,kl))

array([[13,  2,  3, 69, 65, 32],
       [43,  5,  6,  1,  2,  8]])

In [121]:
np.concatenate((m,kl),axis=1)

array([[13,  2,  3, 69, 65, 32],
       [43,  5,  6,  1,  2,  8]])

In [122]:
np.concatenate((m,kl),axis=0)

array([[13,  2,  3],
       [43,  5,  6],
       [69, 65, 32],
       [ 1,  2,  8]])